baseURL = "https://edisongustavo.github.io/"
languageCode = "en-us"
title = "edisongustavo.me"
theme = "beautifulhugo"

[Params]
  subtitle = "Ramblings on Software development, Machine Learning and NLP"
  dateFormat = "January 2, 2006"
  pygmentsCodeFences = true
  pygmentsUseClasses = true

[Author]
  name = "Edison Gustavo Muenz"
  email = "edisongustavo@gmail.com"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 2


[[menu.main]]
    name = "About"
    url = "about"
    weight = 3

